#!/bin/sh /etc/rc.common
START=90
LIST_SEP="
"
CONFIG_TEM="[filter]\nexename=*\n[set]\nAutoRun=1\nShowTrayIcon=1\nShowPopupDlg=1\nShowTrayTips=1\nShowAnimation=0\nport=80,80871\n[info]\nid=mtk7620n\n[update]"

append_params() {
        local p; local v; local s="$1"; shift
        for p in $*; do
                config_get v config "$p"
                IFS="$LIST_SEP"
                for v in $v; do
                        [ -n "$v" ] && (
                                echo ""$p"="$v"" | sed -e 's|_|-|g' >> $config_file
                        )
                done
                unset IFS
        done
}

append_template(){	
	echo -e $CONFIG_TEM > $config_file
	echo "rule=$rule">> $config_file
	echo "[exrule]">> $config_file
	cat $extrule_file>> $config_file
	echo -e "\n[cfg]">> $config_file
	echo "listen-address=$listen_address:$listen_port">> $config_file
}
start_forward(){
	iptables -t nat -N ADBYBY
	iptables -t nat -A ADBYBY -p tcp --dport 80 -j REDIRECT --to-ports $listen_port
	iptables -t nat -I zone_lan_prerouting -j ADBYBY
}
stop_forward(){
	iptables -t nat -D zone_lan_prerouting -j ADBYBY &> /dev/null
	iptables -t nat -F ADBYBY &> /dev/null
	sleep 1
	iptables -t nat -X ADBYBY &> /dev/null
}
start() {
	config_file="/usr/share/adbyby/adhook.ini"
	extrule_file="/usr/share/adbyby/data/extrules.txt"
	config_load "adbyby"	
	local enabled forward rule listen_address listen_port	
	config_get enabled config enabled
	config_get forward config forward	
	config_get rule config rule
	config_get listen_address config listen_address
	config_get listen_port config listen_port
	append_template	
	local s="$1"
	append_params "$s" \
		debug enable_remote_http_toggle \
		buffer_limit keep_alive_timeout socket_timeout log_messages
	[ "$enabled" = '0' ] && { 
		return 0
	} 
	/usr/share/adbyby/adbyby&
	[ "$forward" = '0' ] && {
		stop_forward
		return 0
	}
	start_forward
}	
stop() { 
	service_stop /usr/share/adbyby/adbyby
	sleep 1
	stop_forward
}
